### ISSUE TITLE
TypeError: Foswig is not a constructor

### ISSUE THREAD

**Issue by MarMun** [mrsharpoblunto/foswig.js#21]
I'm pretty sure I miss something fundamental here (and it's not a problem of foswig itself) but let's see:

- I created a new project (`git init ` and `npm init`)
- installed foswig.js (`npm install foswig`)
- set 'type' to 'module' in package.json'
- add your example code to my main.js:

```
import Foswig from 'foswig'

// Create the Markov chain and specify the order of the chain & input dictionary
// The order (an integer that is greater than 0) indicates how many previous 
// letters are taken into account when selecting the next one. A smaller order 
// will result in a more randomized, less recognizeable output. Also, a higher 
// order will result in words which resemble more closely to those in the original 
//dictionary.
const chain = new Foswig(3, [
  "hello",
  "foswig",
])


// Generate a random word with a minimum of 5 characters, a maximum of 10 letters, 
// and that cannot be a match to any of the input dictionaries words.
const constraints = { 
  minLength: 5, 
  maxLength: 10, 
  allowDuplicates: false
}
const word = chain.generate(constraints)

console.log(word)
```

- and try to run this with `node main.js`

I get this error:

```
const chain = new Foswig(3, [
              ^

TypeError: Foswig is not a constructor
    at file:///home/martin/Dev/newname/main.js:11:15
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```
What do I miss?

**Comment by MarMun** [comment]
@mrsharpoblunto Error is gone. Thx a lot!
